# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 656b73e51f94b19f8b6d16b1d939e5e4499a910c453109c5f3096cbc04be3b56165ca0bcf0fd355a115fb075f7b662fa98c25a59c99be06f9adf20a79665611b

test:
  secret_key_base: 9f9d1cc2d28a0b5438f21052a1f6562a0b463dea88ea00a42f03dc4b373d7f256ea77e49d654a2a07c2a39847b393d4da379af3b4100f0415a33cfdbba572e33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
